### ISSUE TITLE
Usage of this library

### ISSUE THREAD

**Issue by ezorfa** [medicalphysics/OpenXRayMC#2]
Hi @medicalphysics !

I came across this library when I googled for a library that produced x-rays from the 3d models of the pelvis. My usecase is to use a graphics library like Open3D and another library which does x-ray imaging. Is this possible with this library?

Many thanks in advance!

**Comment by medicalphysics** [comment]
Hi, sorry this is not possible with this library. OpenDXMC is a frontend for dxmclib, a x-ray dose calculator for voxel geometries. If you want a simulated radiograph from a CT volume check out Siddons algorithm. I don't have any implementations at hand, but it's not that hard to code. Good luck

**Comment by ezorfa** [comment]
@medicalphysics Thanks for your quick response! Do you have any pictures of what this library produces? That would be really helpful to understand the purpose of this library.

**Comment by medicalphysics** [comment]
It's been on my mind for some time. I can't promise anything before Monday. Cheers

**Comment by SARA20210** [comment]
salut! s'il vous plait ,j'ai besoins de la descripton en détaile de l'interface du logiciel OpenDXMC

**Comment by medicalphysics** [comment]
Sorry, but I don't have time to write proper documentation right now. It's in the works togheter with validation of the code, but I can't promise anything before christmas.

**Comment by SARA20210** [comment]
Avant Noël ,c'est très en retardera  pour mes travaux car je suis en train
de travaille sur ce code maintenent et je besoins plus des détailles.


bien cordialement

Le mar. 21 sept. 2021 à 11:46, Erlend Andersen ***@***.***> a
écrit :
